# Emmett's Notebook

In [4]:
import pandas as pd

In [5]:
data = pd.read_csv("contract-rent.csv")

In [6]:
data.head()

,death_date_and_time,manner_of_death,age,sex,race,case_dispo,combined_od1,combined_od2,combined_od3,combined_od4,combined_od5,combined_od6,combined_od7,combined_od8,combined_od9,combined_od10,incident_zip,decedent_zip,case_year
0,2007-01-30T09:22:00,Accidents,45,M,W,MO,Amitriptyline,Demoxepam,Fluoxetine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15143,NaN,2007
1,2007-01-26T14:25:00,Accidents,44,M,W,MO,Alprazolam,Doxepin,Oxycodone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15132,NaN,2007
2,2007-01-31T06:01:00,Accidents,35,F,B,MO,Cocaine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15132,NaN,2007
3,2007-03-05T13:32:00,Accident,34,M,W,MO,Cocaine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15238,NaN,2007
4,2007-03-09T22:22:00,Accidents,43,M,W,MO,Fentanyl,Hydrocodone,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15090,NaN,2007

In [24]:
print("Per-column data:")
print(data["sex"].value_counts())
print("--------------------------")
print(data["combined_od1"].value_counts())
print("-------------------------")
print(data["age"].value_counts())

Per-column data:
M    4012
F    1827
Name: sex, dtype: int64
--------------------------
Fentanyl                      1310
Cocaine                       1129
Alcohol                       1005
Heroin                         507
Alprazolam                     496
                              ...
Magnesium                        1
Delorazepam                      1
2-Fluoro Deschloroketamine       1
Venlafaxine                      1
3-Dimethyl-Butanoic Acid         1
Name: combined_od1, Length: 108, dtype: int64
-------------------------
51    179
34    173
37    166
30    164
52    160
     ...
4       1
83      1
80      1
12      1
91      1
Name: age, Length: 74, dtype: int64

In [26]:
print("Accidents with respect to zip code\n------------------------")
data.groupby("incident_zip")["combined_od1"].value_counts()

Accidents with respect to zip code
------------------------

incident_zip  combined_od1
01201         Methadone        1
01220         Alcohol          1
02601         Amitriptyline    1
03253         Heroin           1
06883         Cocaine          1
                              ..
85379         Alcohol          1
86406         Fentanyl         1
87124         Methadone        1
91352         Fentanyl         1
92405         Cocaine          1
Name: combined_od1, Length: 1620, dtype: int64